---
- name: Rackspace instantiation
  hosts: localhost
  user: root 
  gather_facts: False
  connection: local
  roles:
    - rackspace

- name: Deployment of panalytics
  hosts: panalytics 
  user: root
  gather_facts: False
  roles:
    - absinthe
