---
# tasks file for roles/rackspace

- name: Provision a set of instances
  local_action:
    module: rax
    credentials: "{{ rax_credentials }}"
    name: "{{ rax_name }}"
    flavor: "{{ rax_flavor }}"
    image: "{{ rax_image }}"
    count: "{{ rax_count }}"
    group: panalytics
    wait: yes
    files: 
      ~/.ssh/authorized_keys: ~/.ssh/id_rsa.pub
  register: pacemaker_rax

- name: Add the instances we created (by public IP) to the group {{ group }}
  local_action:
    module: add_host
    credentials: "{{ rax_credentials }}"
    hostname: "{{ item.name }}"
    ansible_ssh_host: "{{ item.rax_accessipv4 }}"
    ansible_ssh_pass: "{{ item.rax_adminpass }}"
    groups: panalytics
  with_items: pacemaker_rax.success
  when: pacemaker_rax.action == 'create'
